### ISSUE TITLE
Preliminary analysis of shocks

### ISSUE THREAD

**Issue by tessam30** [tessam30/Ethiopia#1]
_*Notes: Shocks derived from LSMS 2011/2012 dataset and derived from top two most severe shocks reported by households. All figures account for complex sampling design (survey weights applied)._

![shocks_district pct](https://cloud.githubusercontent.com/assets/5873344/5684300/04f2a9de-97fd-11e4-8ea7-889c120e609a.png)

![shock summary](https://cloud.githubusercontent.com/assets/5873344/5685571/6eabed52-9809-11e4-8617-1d2d2f3bfd2c.png)

![shocks reported](https://cloud.githubusercontent.com/assets/5873344/5684304/0d4e4a3e-97fd-11e4-925c-c4f3c98d87cc.png)

**Comment by flaneuse** [comment]
Note: these need some cleanup in AI @tessam30 .

![image](https://cloud.githubusercontent.com/assets/8041065/8917889/df5a7de6-3482-11e5-8408-6725f8df8153.png)

![image](https://cloud.githubusercontent.com/assets/8041065/8917902/f3b8a79a-3482-11e5-8d0f-6bc11f0c8783.png)

![image](https://cloud.githubusercontent.com/assets/8041065/8917872/c271a894-3482-11e5-974d-fcf659ddd37a.png)

![image](https://cloud.githubusercontent.com/assets/8041065/8917909/fc657c2e-3482-11e5-9692-3ecb72172202.png)
