### ISSUE TITLE
Outstanding data processing

### ISSUE THREAD

**Issue by tessam30** [tessam30/Ethiopia#14]
Instead of the continual bombardment of emails, I thought I'd post the major data tasks on here.    
__Outstanding data processing tasks for Ethiopia LAM:__
- [x] Process community modules to create community access indices as well as major community events. Check if/how the events align to household shocks
- [x]  Process the livestock module to create tropical livestock units (TLUs) for households and other relevant variables mentioned in the needs assessment 
- [x]  Process agriculture modules (post-planting) and create land ownership variables and tenure status. How do landholdings correlate with the food security module response about not owning enough land?  
- [x]  Merge all processed data together, conduct final validation checks, and determine optimal tool for sharing data, products, and GIS info

__Graphics, Maps & Analysis__  
- [x]  Create landscan base map with LSMS regions  
- [x]  Create basemap comparing LSMS survey cluster points with FTF zones of influence  
- [ ]  Create AI compatible graphics for major shocks (price, health, total shocks)
- [x]  Determine appropriate geographic coordinate system and verify all data has been projected before any interpolations or GWRs are executed
- [x]  Create base buffers for 2012 data and 2014 data -- will need to do separate raster masks for the kriging to account for the modifications to the first wave of data
- [x]  Create kriged surfaces and run spatial cluster test for the following:
  - [x]  Shocks  
  - [x]  Food security variables (FCS, dietdiv)
  - [x]  Any other variables of interest as identified in initial needs assessment and follow-up from Mission
- [x]  GWR, spatial filter, and logistic/OLS regressions -- contingent on completion of data processing.  

*Tim and Laura*
- [x]  Create food security graphics summarizing HFIAS index/score, food security perceptions, and dietary diversity and food consumption score patterns
    - [x] dietary diversity over regions
    - [x] FCS score as a function of food type.
    - [x] Plot wealth index factors by wealth quintiles as well as other variables of interest
- [x]  Sketch out and divide data viz tasks @flaneuse

*Patrick and/or Laura *

- [x]  Create AI template or modify UGA version 

__Documentation & Wiki__  
- [x]  Create/update wiki pages to include proper documentation sources and any key notes on data, data processing, or analytical methods that is not easily accessible or memorized (i.e. At what scale is the survey representative? Were sampling weights applied to the creation of regional graphics? etc...)

**Comment by bmccusker** [comment]
I like lists. Keeps me from going crazy and sending too many emails.

**Comment by tessam30** [comment]
Nearly finished with this list.

**Comment by flaneuse** [comment]
list is incomplete.  :)
